### ISSUE TITLE
Feature Request: enable GH labels value

### ISSUE THREAD

**Issue by v1v** [updatecli/policies#33]
### Is your feature request related to a problem?

Customise the GitHub labels for the created PR. So far it's hardcoded as `dependencies` but It would be beneficial if those could be configured with further GH labels

### Solution you'd like

I've seen https://github.com/updatecli/policies/blob/ad4399af013e880420b903d14fa1712e4c88a97d/updatecli/policies/autodiscovery/all/updatecli.d/default.tpl#L67 uses https://github.com/updatecli/policies/blob/ad4399af013e880420b903d14fa1712e4c88a97d/updatecli/policies/autodiscovery/all/values.yaml#L42-L46

Maybe that's how we can support it in the other policies.

But if so, `enabled` might be a breaking change in the other policies.

**Comment by olblak** [comment]
What would you think to expose a new setting `labels` next to `automerge`?

**Comment by v1v** [comment]
Do you mean something like:

```yaml
automerge: false

labels:
  - dependencies
```

Do you think the key `pull_request` can help with?

```yaml

pull_request:
  automerge: false
  labels:
    - dependencies

scm:
  enabled: false
  user: updatecli-bot
  ...
```
